#!/usr/bin/env python3
"""
AN-DNA vNext Phase 1 — Transcript KAT Vector Generator

Generates the exact byte vectors embedded in crates/transcript/src/lib.rs.
Run this to verify Rust/Python parity or to regenerate vectors after a
spec change (which requires version bump + KAT refresh).

Usage:
    python3 tests/generate_transcript_kats.py
    python3 tests/generate_transcript_kats.py --verify  # exits 0 if current vectors match

Dependencies: Python 3.6+ (hashlib.shake_256 is built-in)
"""

import hashlib
import sys

# ── Phase-1 Constants (must match crates/contracts/src/lib.rs) ──

MU_PRE_LEN = 274
TE_V1_LEN = 1336
PK_HASH_LEN = 64
MU_LEN = 64

# mu_pre field offsets
OFF_PK_HASH = 0
OFF_DOMAIN_SEP = 64
OFF_VERSION = 73
OFF_DEVICE_ID32 = 74
OFF_EPOCH = 106
OFF_SID = 114
OFF_ND = 146
OFF_NS = 178
OFF_CTX_HASH = 210
OFF_POLICY_HASH = 242

# T_E field offsets
TE_OFF_RHO = 0
TE_OFF_T1 = 32
TE_OFF_EPOCH = 1312
TE_OFF_DEVICE_ID16 = 1320

DOMAIN_SEP = b"ANDNAAUTH"  # 9 bytes, no hyphen, no NUL
VERSION = 0x01


def shake256(data: bytes, out_len: int) -> bytes:
    return hashlib.shake_256(data).digest(out_len)


def build_te_zeros() -> bytes:
    """KAT-T0: all-zero T_E (1336 bytes)"""
    return bytes(TE_V1_LEN)


def build_te_patterned() -> bytes:
    """KAT-T1: patterned T_E"""
    te = bytearray(TE_V1_LEN)
    # rho = 0x01..0x20
    for i in range(32):
        te[TE_OFF_RHO + i] = i + 1
    # t1 = 0xAA × 1280
    te[TE_OFF_T1:TE_OFF_T1 + 1280] = bytes([0xAA] * 1280)
    # epoch = 5 (u64 LE)
    te[TE_OFF_EPOCH:TE_OFF_EPOCH + 8] = (5).to_bytes(8, "little")
    # device_id16 = 0xBB × 16
    te[TE_OFF_DEVICE_ID16:TE_OFF_DEVICE_ID16 + 16] = bytes([0xBB] * 16)
    return bytes(te)


def build_mu_pre(pk_hash: bytes) -> bytes:
    """KAT-T2: mu_pre with known fields"""
    assert len(pk_hash) == PK_HASH_LEN
    buf = bytearray(MU_PRE_LEN)
    buf[OFF_PK_HASH:OFF_PK_HASH + PK_HASH_LEN] = pk_hash
    buf[OFF_DOMAIN_SEP:OFF_DOMAIN_SEP + len(DOMAIN_SEP)] = DOMAIN_SEP
    buf[OFF_VERSION] = VERSION
    buf[OFF_DEVICE_ID32:OFF_DEVICE_ID32 + 32] = bytes([0xCC] * 32)
    buf[OFF_EPOCH:OFF_EPOCH + 8] = (5).to_bytes(8, "little")
    buf[OFF_SID:OFF_SID + 32] = bytes([0xDD] * 32)
    buf[OFF_ND:OFF_ND + 32] = bytes([0xEE] * 32)
    buf[OFF_NS:OFF_NS + 32] = bytes([0xFF] * 32)
    buf[OFF_CTX_HASH:OFF_CTX_HASH + 32] = bytes([0x11] * 32)
    buf[OFF_POLICY_HASH:OFF_POLICY_HASH + 32] = bytes([0x00] * 32)
    return bytes(buf)


def generate_all():
    # KAT-T0
    te_zero = build_te_zeros()
    pk_hash_t0 = shake256(te_zero, PK_HASH_LEN)

    # KAT-T1
    te_pat = build_te_patterned()
    pk_hash_t1 = shake256(te_pat, PK_HASH_LEN)

    # KAT-T2
    mu_pre = build_mu_pre(pk_hash_t1)
    mu_t2 = shake256(mu_pre, MU_LEN)

    return {
        "KAT_T0_PK_HASH": pk_hash_t0,
        "KAT_T1_PK_HASH": pk_hash_t1,
        "KAT_T2_MU": mu_t2,
        "KAT_T1_TE": te_pat,
        "KAT_T2_MU_PRE": mu_pre,
    }


def fmt_rust_array(name: str, data: bytes) -> str:
    lines = [f"const {name}: [u8; {len(data)}] = ["]
    for i in range(0, len(data), 8):
        chunk = data[i : i + 8]
        hex_str = ", ".join(f"0x{b:02x}" for b in chunk)
        lines.append(f"    {hex_str},")
    lines.append("];")
    return "\n".join(lines)


def main():
    kats = generate_all()

    verify_mode = "--verify" in sys.argv

    if verify_mode:
        # Known expected first-8-byte prefixes
        expected = {
            "KAT_T0_PK_HASH": "0f32d8b356852704",
            "KAT_T1_PK_HASH": "f4338086d8c1148d",
            "KAT_T2_MU": "a508efbf680d8c7f",
        }
        ok = True
        for name, prefix in expected.items():
            actual = kats[name][:8].hex()
            if actual != prefix:
                print(f"FAIL: {name} prefix {actual} != {prefix}")
                ok = False
            else:
                print(f"  OK: {name} prefix {actual}")

        if ok:
            print("\n✓ All KAT prefixes match.")
            sys.exit(0)
        else:
            print("\n✗ KAT verification failed!")
            sys.exit(1)
    else:
        print("// AN-DNA vNext Phase 1 — Transcript KAT Vectors")
        print(f"// Generated by: python3 {sys.argv[0]}")
        print(f"// Python {sys.version.split()[0]}")
        print()
        for name in ["KAT_T0_PK_HASH", "KAT_T1_PK_HASH", "KAT_T2_MU"]:
            print(f"// {name}: first 8 bytes = {kats[name][:8].hex()}")
            print(fmt_rust_array(name, kats[name]))
            print()

        # Also validate internal consistency
        print("// ── Internal consistency checks ──")
        print(f"// TE_V1_LEN = {len(kats['KAT_T1_TE'])}")
        print(f"// MU_PRE_LEN = {len(kats['KAT_T2_MU_PRE'])}")
        print(f"// domain_sep @ [64:73] = {kats['KAT_T2_MU_PRE'][64:73]}")
        print(f"// version @ [73] = 0x{kats['KAT_T2_MU_PRE'][73]:02x}")
        assert kats["KAT_T2_MU_PRE"][64:73] == DOMAIN_SEP
        assert kats["KAT_T2_MU_PRE"][73] == VERSION
        print("\n✓ All internal consistency checks passed.")


if __name__ == "__main__":
    main()
