[package]
name = "ffi-cli"
version.workspace = true
edition.workspace = true

[features]
default = ["oqs-backend"]
oqs-backend = ["andna-ffi/oqs-backend"]
stub = ["andna-ffi/stub"]
fips-integrity-stub = ["andna-ffi/fips-integrity-stub"]
fips-kat-vectors-embedded = ["andna-ffi/fips-kat-vectors-embedded"]

[dependencies]
serde = { version = "1", features = ["derive"] }
andna-contracts = { workspace = true }
andna-ffi = { path = "../crates/ffi", default-features = false }
sha2 = "0.10"
serde_json = { workspace = true }
sha3 = "0.10"
andna-audit = { version = "0.1.0", path = "../crates/audit" }

[[bin]]
name = "andna"
path = "src/main.rs"
