[package]
name = "ffi-cli"
version.workspace = true
edition.workspace = true

[features]
default = ["oqs-backend"]
oqs-backend = ["andna-ffi/oqs-backend"]
stub = ["andna-ffi/stub"]

[dependencies]
serde = { version = "1", features = ["derive"] }
andna-contracts = { workspace = true }
andna-ffi = { path = "../crates/ffi", default-features = false }
sha2 = "0.10"
serde_json = { workspace = true }
sha3 = "0.10"

[[bin]]
name = "andna"
path = "src/main.rs"
