//! # AN-DNA Contracts Code Generator
//!
//! Generates `include/andna_vnext_contracts.h` from the Rust contracts crate.
//! This ensures C consumers share the exact same constants with `_Static_assert`
//! anti-drift guards.
//!
//! Usage: `cargo run -p contracts_codegen -- generate`

use andna_contracts::*;
use std::io::Write;

fn main() {
    let args: Vec<String> = std::env::args().collect();
    if args.len() < 2 || args[1] != "generate" {
        eprintln!("Usage: cargo run -p contracts_codegen -- generate");
        std::process::exit(1);
    }

    let header = generate_header();
    let out_path = std::path::Path::new("include/andna_vnext_contracts.h");

    if let Some(parent) = out_path.parent() {
        std::fs::create_dir_all(parent).expect("create include/");
    }

    let mut f = std::fs::File::create(out_path).expect("create header file");
    f.write_all(header.as_bytes()).expect("write header");

    println!("Generated: {}", out_path.display());
}

fn generate_header() -> String {
    let mut h = String::new();

    h.push_str("/* ================================================================\n");
    h.push_str(" * andna_vnext_contracts.h — AUTO-GENERATED, DO NOT HAND EDIT\n");
    h.push_str(" *\n");
    h.push_str(" * Generated by: cargo run -p contracts_codegen -- generate\n");
    h.push_str(" * Source of truth: crates/contracts/src/lib.rs\n");
    h.push_str(" * ================================================================ */\n\n");
    h.push_str("#ifndef ANDNA_VNEXT_CONTRACTS_H\n");
    h.push_str("#define ANDNA_VNEXT_CONTRACTS_H\n\n");
    h.push_str("#include <stdint.h>\n");
    h.push_str("#include <stddef.h>\n\n");

    // ── ML-DSA-44 Constants ──
    h.push_str("/* ── ML-DSA-44 Ring Constants (FIPS 204, Category 2) ── */\n");
    emit_u32(&mut h, "ANDNA_MLDSA44_Q", MLDSA44_Q);
    emit_usize(&mut h, "ANDNA_MLDSA44_N", MLDSA44_N);
    emit_usize(&mut h, "ANDNA_MLDSA44_K", MLDSA44_K);
    emit_usize(&mut h, "ANDNA_MLDSA44_ELL", MLDSA44_ELL);
    emit_usize(&mut h, "ANDNA_MLDSA44_D", MLDSA44_D);
    emit_usize(&mut h, "ANDNA_MLDSA44_ETA", MLDSA44_ETA);
    emit_usize(&mut h, "ANDNA_MLDSA44_TAU", MLDSA44_TAU);
    emit_usize(&mut h, "ANDNA_MLDSA44_OMEGA", MLDSA44_OMEGA);
    emit_u32(&mut h, "ANDNA_MLDSA44_GAMMA1", MLDSA44_GAMMA1);
    emit_u32(&mut h, "ANDNA_MLDSA44_GAMMA2", MLDSA44_GAMMA2);
    emit_u32(&mut h, "ANDNA_MLDSA44_ALPHA", MLDSA44_ALPHA);
    emit_u32(&mut h, "ANDNA_MLDSA44_BETA", MLDSA44_BETA);
    h.push('\n');

    // ── Domain Separation ──
    h.push_str("/* ── Domain Separation ── */\n");
    emit_usize(&mut h, "ANDNA_DOMAIN_SEP_LEN", DOMAIN_SEP_LEN);
    h.push_str("/* Phase-1 canonical: \"ANDNAAUTH\" (no hyphen, no NUL) */\n");
    h.push_str("/* Hex: 41 4E 44 4E 41 41 55 54 48 */\n");
    h.push_str("static const uint8_t ANDNA_DOMAIN_SEP[9] = {\n");
    h.push_str("    ");
    for (i, &b) in DOMAIN_SEP.iter().enumerate() {
        if i > 0 { h.push_str(", "); }
        h.push_str(&format!("0x{:02X}", b));
    }
    h.push_str("\n}; /* ");
    for &b in DOMAIN_SEP.iter() {
        h.push(b as char);
    }
    h.push_str(" */\n");
    h.push_str("/* V2 (future): \"ANDNA-AUTH\" = 10 bytes, under MU_PRE_VERSION 0x02 */\n");
    emit_usize(&mut h, "ANDNA_DOMAIN_SEP_V2_LEN", DOMAIN_SEP_V2_LEN);
    h.push('\n');

    // ── mu_pre ──
    h.push_str("/* ── mu_pre Layout (274 bytes) ── */\n");
    emit_usize(&mut h, "ANDNA_MU_PRE_LEN", MU_PRE_LEN);
    emit_usize(&mut h, "ANDNA_MU_PRE_PK_HASH_OFF", MU_PRE_PK_HASH_OFF);
    emit_usize(&mut h, "ANDNA_MU_PRE_PK_HASH_LEN", MU_PRE_PK_HASH_LEN);
    emit_usize(&mut h, "ANDNA_MU_PRE_DOMAIN_SEP_OFF", MU_PRE_DOMAIN_SEP_OFF);
    emit_usize(&mut h, "ANDNA_MU_PRE_DOMAIN_SEP_LEN", MU_PRE_DOMAIN_SEP_LEN);
    emit_usize(&mut h, "ANDNA_MU_PRE_VERSION_OFF", MU_PRE_VERSION_OFF);
    emit_usize(&mut h, "ANDNA_MU_PRE_VERSION_LEN", MU_PRE_VERSION_LEN);
    emit_u8(&mut h, "ANDNA_MU_PRE_VERSION_VAL", MU_PRE_VERSION_VAL);
    emit_usize(&mut h, "ANDNA_MU_PRE_DEVICE_ID32_OFF", MU_PRE_DEVICE_ID32_OFF);
    emit_usize(&mut h, "ANDNA_MU_PRE_DEVICE_ID32_LEN", MU_PRE_DEVICE_ID32_LEN);
    emit_usize(&mut h, "ANDNA_MU_PRE_EPOCH_OFF", MU_PRE_EPOCH_OFF);
    emit_usize(&mut h, "ANDNA_MU_PRE_EPOCH_LEN", MU_PRE_EPOCH_LEN);
    emit_usize(&mut h, "ANDNA_MU_PRE_SID_OFF", MU_PRE_SID_OFF);
    emit_usize(&mut h, "ANDNA_MU_PRE_SID_LEN", MU_PRE_SID_LEN);
    emit_usize(&mut h, "ANDNA_MU_PRE_ND_OFF", MU_PRE_ND_OFF);
    emit_usize(&mut h, "ANDNA_MU_PRE_ND_LEN", MU_PRE_ND_LEN);
    emit_usize(&mut h, "ANDNA_MU_PRE_NS_OFF", MU_PRE_NS_OFF);
    emit_usize(&mut h, "ANDNA_MU_PRE_NS_LEN", MU_PRE_NS_LEN);
    emit_usize(&mut h, "ANDNA_MU_PRE_CTX_HASH_OFF", MU_PRE_CTX_HASH_OFF);
    emit_usize(&mut h, "ANDNA_MU_PRE_CTX_HASH_LEN", MU_PRE_CTX_HASH_LEN);
    emit_usize(&mut h, "ANDNA_MU_PRE_POLICY_HASH_OFF", MU_PRE_POLICY_HASH_OFF);
    emit_usize(&mut h, "ANDNA_MU_PRE_POLICY_HASH_LEN", MU_PRE_POLICY_HASH_LEN);
    h.push('\n');

    // ── T_E ──
    h.push_str("/* ── T_E Layout ── */\n");
    emit_usize(&mut h, "ANDNA_TE_RHO_OFF", TE_RHO_OFF);
    emit_usize(&mut h, "ANDNA_TE_RHO_LEN", TE_RHO_LEN);
    emit_usize(&mut h, "ANDNA_TE_T1_OFF", TE_T1_OFF);
    emit_usize(&mut h, "ANDNA_TE_T1_LEN", TE_T1_LEN);
    emit_usize(&mut h, "ANDNA_TE_EPOCH_OFF", TE_EPOCH_OFF);
    emit_usize(&mut h, "ANDNA_TE_EPOCH_LEN", TE_EPOCH_LEN);
    emit_usize(&mut h, "ANDNA_TE_DEVICE_ID16_OFF", TE_DEVICE_ID16_OFF);
    emit_usize(&mut h, "ANDNA_TE_DEVICE_ID16_LEN", TE_DEVICE_ID16_LEN);
    emit_usize(&mut h, "ANDNA_TE_V1_LEN", TE_V1_LEN);
    emit_usize(&mut h, "ANDNA_TE_V2_LEN", TE_V2_LEN);
    emit_usize(&mut h, "ANDNA_TE_LEN", TE_LEN);
    h.push('\n');

    // ── Signature ──
    h.push_str("/* ── ML-DSA-44 Signature (2420 bytes) ── */\n");
    emit_usize(&mut h, "ANDNA_SIG_Z_OFF", SIG_Z_OFF);
    emit_usize(&mut h, "ANDNA_SIG_Z_LEN", SIG_Z_LEN);
    emit_usize(&mut h, "ANDNA_SIG_H_OFF", SIG_H_OFF);
    emit_usize(&mut h, "ANDNA_SIG_H_LEN", SIG_H_LEN);
    emit_usize(&mut h, "ANDNA_SIG_C_TILDE_OFF", SIG_C_TILDE_OFF);
    emit_usize(&mut h, "ANDNA_SIG_C_TILDE_LEN", SIG_C_TILDE_LEN);
    emit_usize(&mut h, "ANDNA_SIG_LEN", SIG_LEN);
    h.push('\n');

    // ── Frame v2 ──
    h.push_str("/* ── Frame v2 (fixed 4030 bytes) ── */\n");
    emit_usize(&mut h, "ANDNA_FRAME_V2_MU_PRE_OFF", FRAME_V2_MU_PRE_OFF);
    emit_usize(&mut h, "ANDNA_FRAME_V2_TE_OFF", FRAME_V2_TE_OFF);
    emit_usize(&mut h, "ANDNA_FRAME_V2_SIG_OFF", FRAME_V2_SIG_OFF);
    emit_usize(&mut h, "ANDNA_FRAME_V2_LEN", FRAME_V2_LEN);
    h.push('\n');

    // ── _Static_assert anti-drift guards ──
    h.push_str("/* ── Anti-Drift Guards ── */\n");
    assert_eq(&mut h, "ANDNA_MU_PRE_LEN", 274);
    assert_eq(&mut h, "ANDNA_TE_V1_LEN", 1336);
    assert_eq(&mut h, "ANDNA_TE_V2_LEN", 1352);
    assert_eq(&mut h, "ANDNA_TE_LEN", 1336);
    assert_eq(&mut h, "ANDNA_SIG_LEN", 2420);
    assert_eq(&mut h, "ANDNA_FRAME_V2_LEN", 4030);
    assert_eq(&mut h, "ANDNA_MLDSA44_BETA", 78);
    assert_eq(&mut h, "ANDNA_MLDSA44_GAMMA1", 131072);
    assert_eq(&mut h, "ANDNA_MLDSA44_GAMMA2", 95232);

    // Field sum checks
    h.push_str("_Static_assert(\n");
    h.push_str("    ANDNA_MU_PRE_PK_HASH_LEN + ANDNA_MU_PRE_DOMAIN_SEP_LEN +\n");
    h.push_str("    ANDNA_MU_PRE_VERSION_LEN + ANDNA_MU_PRE_DEVICE_ID32_LEN +\n");
    h.push_str("    ANDNA_MU_PRE_EPOCH_LEN + ANDNA_MU_PRE_SID_LEN +\n");
    h.push_str("    ANDNA_MU_PRE_ND_LEN + ANDNA_MU_PRE_NS_LEN +\n");
    h.push_str("    ANDNA_MU_PRE_CTX_HASH_LEN + ANDNA_MU_PRE_POLICY_HASH_LEN\n");
    h.push_str("    == ANDNA_MU_PRE_LEN,\n");
    h.push_str("    \"mu_pre field sum != MU_PRE_LEN\");\n");

    h.push_str("_Static_assert(\n");
    h.push_str("    ANDNA_TE_RHO_LEN + ANDNA_TE_T1_LEN +\n");
    h.push_str("    ANDNA_TE_EPOCH_LEN + ANDNA_TE_DEVICE_ID16_LEN\n");
    h.push_str("    == ANDNA_TE_V1_LEN,\n");
    h.push_str("    \"TE field sum != TE_V1_LEN\");\n");

    h.push_str("_Static_assert(\n");
    h.push_str("    ANDNA_SIG_Z_LEN + ANDNA_SIG_H_LEN + ANDNA_SIG_C_TILDE_LEN\n");
    h.push_str("    == ANDNA_SIG_LEN,\n");
    h.push_str("    \"sig field sum != SIG_LEN\");\n");

    h.push_str("_Static_assert(\n");
    h.push_str("    ANDNA_MU_PRE_LEN + ANDNA_TE_LEN + ANDNA_SIG_LEN\n");
    h.push_str("    == ANDNA_FRAME_V2_LEN,\n");
    h.push_str("    \"frame field sum != FRAME_V2_LEN\");\n\n");

    // ── mu_pre offset-chain contiguity ──
    h.push_str("/* ── mu_pre Offset-Chain Contiguity Guards ── */\n");
    offset_chain(&mut h, "MU_PRE_PK_HASH", "MU_PRE_DOMAIN_SEP", "MU_PRE_PK_HASH");
    offset_chain(&mut h, "MU_PRE_DOMAIN_SEP", "MU_PRE_VERSION", "MU_PRE_DOMAIN_SEP");
    offset_chain(&mut h, "MU_PRE_VERSION", "MU_PRE_DEVICE_ID32", "MU_PRE_VERSION");
    offset_chain(&mut h, "MU_PRE_DEVICE_ID32", "MU_PRE_EPOCH", "MU_PRE_DEVICE_ID32");
    offset_chain(&mut h, "MU_PRE_EPOCH", "MU_PRE_SID", "MU_PRE_EPOCH");
    offset_chain(&mut h, "MU_PRE_SID", "MU_PRE_ND", "MU_PRE_SID");
    offset_chain(&mut h, "MU_PRE_ND", "MU_PRE_NS", "MU_PRE_ND");
    offset_chain(&mut h, "MU_PRE_NS", "MU_PRE_CTX_HASH", "MU_PRE_NS");
    offset_chain(&mut h, "MU_PRE_CTX_HASH", "MU_PRE_POLICY_HASH", "MU_PRE_CTX_HASH");
    h.push_str("_Static_assert(\n");
    h.push_str("    ANDNA_MU_PRE_POLICY_HASH_OFF + ANDNA_MU_PRE_POLICY_HASH_LEN\n");
    h.push_str("    == ANDNA_MU_PRE_LEN,\n");
    h.push_str("    \"mu_pre tail does not reach MU_PRE_LEN\");\n\n");

    // ── T_E offset-chain contiguity ──
    h.push_str("/* ── T_E Offset-Chain Contiguity Guards ── */\n");
    offset_chain(&mut h, "TE_RHO", "TE_T1", "TE_RHO");
    offset_chain(&mut h, "TE_T1", "TE_EPOCH", "TE_T1");
    offset_chain(&mut h, "TE_EPOCH", "TE_DEVICE_ID16", "TE_EPOCH");
    h.push_str("_Static_assert(\n");
    h.push_str("    ANDNA_TE_DEVICE_ID16_OFF + ANDNA_TE_DEVICE_ID16_LEN\n");
    h.push_str("    == ANDNA_TE_V1_LEN,\n");
    h.push_str("    \"TE tail does not reach TE_V1_LEN\");\n\n");

    // ── Signature offset-chain contiguity ──
    h.push_str("/* ── Signature Offset-Chain Contiguity Guards ── */\n");
    offset_chain(&mut h, "SIG_Z", "SIG_H", "SIG_Z");
    offset_chain(&mut h, "SIG_H", "SIG_C_TILDE", "SIG_H");
    h.push_str("_Static_assert(\n");
    h.push_str("    ANDNA_SIG_C_TILDE_OFF + ANDNA_SIG_C_TILDE_LEN\n");
    h.push_str("    == ANDNA_SIG_LEN,\n");
    h.push_str("    \"sig tail does not reach SIG_LEN\");\n\n");

    h.push_str("#endif /* ANDNA_VNEXT_CONTRACTS_H */\n");
    h
}

fn emit_usize(h: &mut String, name: &str, val: usize) {
    h.push_str(&format!("#define {} {}u\n", name, val));
}

fn emit_u32(h: &mut String, name: &str, val: u32) {
    h.push_str(&format!("#define {} {}u\n", name, val));
}

fn emit_u8(h: &mut String, name: &str, val: u8) {
    h.push_str(&format!("#define {} 0x{:02X}u\n", name, val));
}

fn assert_eq(h: &mut String, name: &str, val: usize) {
    h.push_str(&format!(
        "_Static_assert({} == {}u, \"{} drift detected\");\n",
        name, val, name
    ));
}

fn offset_chain(h: &mut String, current: &str, next: &str, current_len: &str) {
    h.push_str(&format!(
        "_Static_assert(ANDNA_{}_OFF ==\n    ANDNA_{}_OFF + ANDNA_{}_LEN,\n    \"{} offset non-contiguous\");\n",
        next, current, current_len, next
    ));
}
