//! # AN-DNA Transcript — SHAKE256 hashing and transcript construction
//!
//! Real implementation of:
//! - `pk_hash_from_te`: SHAKE256(Encode(T_E), 64) → 64-byte pk_hash
//! - `mu_from_mu_pre`: SHAKE256(mu_pre, 64) → 64-byte μ
//! - `pk_hash_check`: constant-time comparison of mu_pre[0..64] vs pk_hash(te)

#![forbid(unsafe_code)]

use andna_contracts::*;
use sha3::digest::{ExtendableOutput, Update, XofReader};
use sha3::Shake256;
use subtle::ConstantTimeEq;
use zeroize::Zeroize;

/// Transcript error type.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TranscriptError {
    /// mu_pre[0..64] does not match SHAKE256(Encode(T_E), 64).
    PkHashMismatch,
    /// mu_pre.epoch != T_E.epoch (stale epoch / Frankenstein payload).
    EpochMismatch,
    /// device_id32 != SHAKE256(device_id16, 32).
    DeviceIdMismatch,
}

/// Compute pk_hash = SHAKE256(te_bytes, 64).
///
/// Input: the full T_E v1 byte array (1336 bytes).
/// Output: 64-byte hash written to `out`.
pub fn pk_hash_from_te(te: &[u8; TE_LEN], out: &mut [u8; PK_HASH_LEN]) {
    let mut hasher = Shake256::default();
    hasher.update(te);
    let mut reader = hasher.finalize_xof();
    reader.read(out);
}

/// Compute μ = SHAKE256(mu_pre, 64).
///
/// Input: the full 274-byte mu_pre buffer.
/// Output: 64-byte μ written to `out`.
pub fn mu_from_mu_pre(mu_pre: &[u8; MU_PRE_LEN], out: &mut [u8; MU_LEN]) {
    let mut hasher = Shake256::default();
    hasher.update(mu_pre);
    let mut reader = hasher.finalize_xof();
    reader.read(out);
}

/// Verify that mu_pre[0..64] == SHAKE256(Encode(T_E), 64).
///
/// Uses constant-time comparison via `subtle::ConstantTimeEq`.
pub fn check_pk_hash_binding(
    mu_pre: &[u8; MU_PRE_LEN],
    te: &[u8; TE_LEN],
) -> Result<(), TranscriptError> {
    let mut expected = [0u8; PK_HASH_LEN];
    pk_hash_from_te(te, &mut expected);

    let embedded = &mu_pre[MU_PRE_PK_HASH_OFF..MU_PRE_PK_HASH_OFF + MU_PRE_PK_HASH_LEN];

    let eq = embedded.ct_eq(&expected);
    expected.zeroize();

    if eq.into() {
        Ok(())
    } else {
        Err(TranscriptError::PkHashMismatch)
    }
}

/// Derive device_id32 = SHAKE256(device_id16, 32).
///
/// The 16-byte UUID in T_E is the native hardware root.
/// The 32-byte ID in mu_pre is the mathematically expanded payload slot.
pub fn device_id32_from_id16(
    device_id16: &[u8; TE_DEVICE_ID16_LEN],
) -> [u8; MU_PRE_DEVICE_ID32_LEN] {
    let mut hasher = Shake256::default();
    hasher.update(device_id16);
    let mut out = [0u8; MU_PRE_DEVICE_ID32_LEN];
    hasher.finalize_xof().read(&mut out);
    out
}

/// Directive B: Check that mu_pre.epoch == T_E.epoch.
///
/// Prevents "Frankenstein" payloads where mu_pre binds to one epoch
/// but T_E belongs to another.
pub fn check_epoch_correlation(
    mu_pre: &[u8; MU_PRE_LEN],
    te: &[u8; TE_LEN],
) -> Result<(), TranscriptError> {
    let mut mp_epoch_bytes = [0u8; 8];
    mp_epoch_bytes.copy_from_slice(&mu_pre[MU_PRE_EPOCH_OFF..MU_PRE_EPOCH_OFF + MU_PRE_EPOCH_LEN]);
    let mut te_epoch_bytes = [0u8; 8];
    te_epoch_bytes.copy_from_slice(&te[TE_EPOCH_OFF..TE_EPOCH_OFF + TE_EPOCH_LEN]);

    // Constant-time comparison of the 8 epoch bytes
    if mp_epoch_bytes.ct_eq(&te_epoch_bytes).into() {
        Ok(())
    } else {
        Err(TranscriptError::EpochMismatch)
    }
}

/// Directive E: Check that mu_pre.device_id32 == SHAKE256(T_E.device_id16, 32).
///
/// Enforces the device ID duality invariant: the 32-byte expanded ID
/// in mu_pre must be the deterministic derivation of the 16-byte UUID in T_E.
pub fn check_device_id_duality(
    mu_pre: &[u8; MU_PRE_LEN],
    te: &[u8; TE_LEN],
) -> Result<(), TranscriptError> {
    let embedded_id32 =
        &mu_pre[MU_PRE_DEVICE_ID32_OFF..MU_PRE_DEVICE_ID32_OFF + MU_PRE_DEVICE_ID32_LEN];

    let device_id16: &[u8; TE_DEVICE_ID16_LEN] = te
        [TE_DEVICE_ID16_OFF..TE_DEVICE_ID16_OFF + TE_DEVICE_ID16_LEN]
        .try_into()
        .expect("compile-time size guarantees this");

    let mut expected = device_id32_from_id16(device_id16);
    let eq = embedded_id32.ct_eq(&expected);
    expected.zeroize();

    if eq.into() {
        Ok(())
    } else {
        Err(TranscriptError::DeviceIdMismatch)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // ====================================================================
    // KAT vectors — generated by Python hashlib.shake_256, byte-identical
    // to the Phase-1 reference in andna/vnext/mu_pre.py.
    //
    // Regenerate with:
    //   python3 tests/generate_transcript_kats.py
    // ====================================================================

    /// KAT-T0: pk_hash = SHAKE256(zeros(1336), 64)
    const KAT_T0_PK_HASH: [u8; 64] = [
        0x0f, 0x32, 0xd8, 0xb3, 0x56, 0x85, 0x27, 0x04, 0x9e, 0x8d, 0x40, 0xf3, 0xca, 0x7a, 0xa2,
        0xc9, 0x24, 0xe3, 0x5d, 0xdd, 0x64, 0x98, 0xe5, 0x84, 0xf1, 0xd9, 0xec, 0x34, 0x39, 0x4f,
        0x3b, 0xc4, 0x2e, 0x32, 0x22, 0x67, 0x5c, 0xc3, 0x63, 0xe0, 0x63, 0x78, 0x9d, 0xaa, 0x9e,
        0xf6, 0x1a, 0x89, 0x94, 0x82, 0xc3, 0x9c, 0xad, 0xa2, 0x14, 0xd9, 0x84, 0xfd, 0x94, 0xbe,
        0x5b, 0xb4, 0xb5, 0x29,
    ];

    /// KAT-T1: pk_hash = SHAKE256(patterned_te, 64)
    /// T_E: rho = 01..20, t1 = 0xAA×1280, epoch = 5 LE, id16 = 0xBB×16
    const KAT_T1_PK_HASH: [u8; 64] = [
        0xf4, 0x33, 0x80, 0x86, 0xd8, 0xc1, 0x14, 0x8d, 0xaa, 0x60, 0x8e, 0xd1, 0x72, 0x8e, 0x63,
        0xe7, 0x0f, 0x87, 0xc0, 0xe6, 0xdf, 0x1c, 0x1a, 0x17, 0xaf, 0xa5, 0x6c, 0xb4, 0x2c, 0x56,
        0x36, 0x5d, 0xdb, 0xad, 0x5c, 0xc2, 0x4d, 0x39, 0xbb, 0x64, 0x30, 0xae, 0x16, 0x77, 0xbe,
        0xe3, 0x63, 0x7a, 0xcc, 0x88, 0x6f, 0xd2, 0xe0, 0x87, 0xd8, 0xe2, 0x8f, 0x16, 0x0c, 0xe0,
        0xb6, 0x4a, 0xc8, 0x74,
    ];

    /// KAT-T2: mu = SHAKE256(known_mu_pre, 64)
    /// mu_pre built with KAT-T1 pk_hash, ANDNAAUTH, version 0x01,
    /// device_id32=0xCC, epoch=5, sid=0xDD, N_d=0xEE, N_s=0xFF,
    /// ctx_hash=0x11, policy_hash=0x00
    const KAT_T2_MU: [u8; 64] = [
        0xa5, 0x08, 0xef, 0xbf, 0x68, 0x0d, 0x8c, 0x7f, 0x32, 0x88, 0x00, 0x43, 0x4e, 0x09, 0xe7,
        0x38, 0x60, 0x7f, 0x4a, 0xfc, 0x2b, 0xde, 0x2e, 0xc8, 0x03, 0x5d, 0x09, 0x2d, 0xdb, 0xab,
        0x0d, 0xb0, 0xcb, 0x5c, 0xba, 0xac, 0x71, 0x6a, 0xc2, 0x80, 0x38, 0xf2, 0xec, 0xa2, 0xb7,
        0xe1, 0x96, 0x50, 0xaf, 0x2d, 0x1c, 0xe1, 0xa1, 0xb8, 0x9c, 0xa9, 0x59, 0xcd, 0x1c, 0x5a,
        0xfe, 0xbb, 0x21, 0x3a,
    ];

    // ── Helper: build KAT-T1 T_E ──

    fn build_kat_t1_te() -> [u8; TE_LEN] {
        let mut te = [0u8; TE_LEN];
        // rho = 0x01..0x20
        for i in 0..32 {
            te[TE_RHO_OFF + i] = (i + 1) as u8;
        }
        // t1 = 0xAA × 1280
        te[TE_T1_OFF..TE_T1_OFF + TE_T1_LEN].fill(0xAA);
        // epoch = 5 LE
        te[TE_EPOCH_OFF..TE_EPOCH_OFF + TE_EPOCH_LEN].copy_from_slice(&5u64.to_le_bytes());
        // device_id16 = 0xBB × 16
        te[TE_DEVICE_ID16_OFF..TE_DEVICE_ID16_OFF + TE_DEVICE_ID16_LEN].fill(0xBB);
        te
    }

    // ── Helper: build KAT-T2 mu_pre ──

    fn build_kat_t2_mu_pre(pk_hash: &[u8; PK_HASH_LEN]) -> [u8; MU_PRE_LEN] {
        let mut mp = [0u8; MU_PRE_LEN];
        mp[MU_PRE_PK_HASH_OFF..MU_PRE_PK_HASH_OFF + PK_HASH_LEN].copy_from_slice(pk_hash);
        mp[MU_PRE_DOMAIN_SEP_OFF..MU_PRE_DOMAIN_SEP_OFF + DOMAIN_SEP_LEN]
            .copy_from_slice(&DOMAIN_SEP);
        mp[MU_PRE_VERSION_OFF] = MU_PRE_VERSION_VAL;
        mp[MU_PRE_DEVICE_ID32_OFF..MU_PRE_DEVICE_ID32_OFF + MU_PRE_DEVICE_ID32_LEN].fill(0xCC);
        mp[MU_PRE_EPOCH_OFF..MU_PRE_EPOCH_OFF + MU_PRE_EPOCH_LEN]
            .copy_from_slice(&5u64.to_le_bytes());
        mp[MU_PRE_SID_OFF..MU_PRE_SID_OFF + MU_PRE_SID_LEN].fill(0xDD);
        mp[MU_PRE_ND_OFF..MU_PRE_ND_OFF + MU_PRE_ND_LEN].fill(0xEE);
        mp[MU_PRE_NS_OFF..MU_PRE_NS_OFF + MU_PRE_NS_LEN].fill(0xFF);
        mp[MU_PRE_CTX_HASH_OFF..MU_PRE_CTX_HASH_OFF + MU_PRE_CTX_HASH_LEN].fill(0x11);
        mp[MU_PRE_POLICY_HASH_OFF..MU_PRE_POLICY_HASH_OFF + MU_PRE_POLICY_HASH_LEN].fill(0x00);
        mp
    }

    // ====================================================================
    // KAT Tests — byte-for-byte parity with Python reference
    // ====================================================================

    #[test]
    fn kat_t0_pk_hash_zeros() {
        let te = [0u8; TE_LEN];
        let mut out = [0u8; PK_HASH_LEN];
        pk_hash_from_te(&te, &mut out);
        assert_eq!(
            out, KAT_T0_PK_HASH,
            "KAT-T0 failed: pk_hash(zeros) diverges from Python reference"
        );
    }

    #[test]
    fn kat_t1_pk_hash_patterned() {
        let te = build_kat_t1_te();
        let mut out = [0u8; PK_HASH_LEN];
        pk_hash_from_te(&te, &mut out);
        assert_eq!(
            out, KAT_T1_PK_HASH,
            "KAT-T1 failed: pk_hash(patterned_te) diverges from Python reference"
        );
    }

    #[test]
    fn kat_t2_mu_from_mu_pre() {
        let te = build_kat_t1_te();
        let mut pk_hash = [0u8; PK_HASH_LEN];
        pk_hash_from_te(&te, &mut pk_hash);

        // Verify pk_hash matches KAT-T1 (dependency chain)
        assert_eq!(pk_hash, KAT_T1_PK_HASH, "KAT-T2 setup: pk_hash mismatch");

        let mu_pre = build_kat_t2_mu_pre(&pk_hash);
        let mut mu = [0u8; MU_LEN];
        mu_from_mu_pre(&mu_pre, &mut mu);
        assert_eq!(
            mu, KAT_T2_MU,
            "KAT-T2 failed: mu(known_mu_pre) diverges from Python reference"
        );
    }

    #[test]
    fn kat_t2_mu_pre_domain_sep_is_andnaauth() {
        let te = build_kat_t1_te();
        let mut pk_hash = [0u8; PK_HASH_LEN];
        pk_hash_from_te(&te, &mut pk_hash);
        let mu_pre = build_kat_t2_mu_pre(&pk_hash);

        // Verify domain separator bytes at offset 64..73
        assert_eq!(
            &mu_pre[MU_PRE_DOMAIN_SEP_OFF..MU_PRE_DOMAIN_SEP_OFF + DOMAIN_SEP_LEN],
            b"ANDNAAUTH",
            "Domain separator must be ANDNAAUTH (9 bytes, no hyphen)"
        );
    }

    #[test]
    fn kat_t2_mu_pre_version_byte() {
        let te = build_kat_t1_te();
        let mut pk_hash = [0u8; PK_HASH_LEN];
        pk_hash_from_te(&te, &mut pk_hash);
        let mu_pre = build_kat_t2_mu_pre(&pk_hash);

        assert_eq!(mu_pre[MU_PRE_VERSION_OFF], 0x01, "Version must be 0x01");
    }

    // ====================================================================
    // Differential harness — round-trip pk_hash binding check
    // ====================================================================

    #[test]
    fn differential_pk_hash_binding_kat_t1() {
        let te = build_kat_t1_te();
        let mut pk_hash = [0u8; PK_HASH_LEN];
        pk_hash_from_te(&te, &mut pk_hash);
        let mu_pre = build_kat_t2_mu_pre(&pk_hash);

        assert!(
            check_pk_hash_binding(&mu_pre, &te).is_ok(),
            "Binding check must pass for correctly-constructed mu_pre"
        );
    }

    #[test]
    fn differential_pk_hash_binding_rejects_wrong_te() {
        let te_good = build_kat_t1_te();
        let mut pk_hash = [0u8; PK_HASH_LEN];
        pk_hash_from_te(&te_good, &mut pk_hash);
        let mu_pre = build_kat_t2_mu_pre(&pk_hash);

        // Flip one bit in T_E
        let mut te_bad = te_good;
        te_bad[0] ^= 0x01;

        assert_eq!(
            check_pk_hash_binding(&mu_pre, &te_bad),
            Err(TranscriptError::PkHashMismatch),
            "Binding check must reject when T_E differs by even 1 bit"
        );
    }

    #[test]
    fn differential_pk_hash_binding_rejects_tampered_pk_hash() {
        let te = build_kat_t1_te();
        let mut pk_hash = [0u8; PK_HASH_LEN];
        pk_hash_from_te(&te, &mut pk_hash);
        let mut mu_pre = build_kat_t2_mu_pre(&pk_hash);

        // Tamper one byte in the embedded pk_hash
        mu_pre[0] ^= 0x01;

        assert_eq!(
            check_pk_hash_binding(&mu_pre, &te),
            Err(TranscriptError::PkHashMismatch),
            "Binding check must reject when embedded pk_hash is tampered"
        );
    }

    // ====================================================================
    // Original property tests (kept for regression)
    // ====================================================================

    #[test]
    fn pk_hash_deterministic() {
        let te = [0x42u8; TE_LEN];
        let mut h1 = [0u8; PK_HASH_LEN];
        let mut h2 = [0u8; PK_HASH_LEN];
        pk_hash_from_te(&te, &mut h1);
        pk_hash_from_te(&te, &mut h2);
        assert_eq!(h1, h2);
    }

    #[test]
    fn pk_hash_differs_on_different_input() {
        let te_a = [0x00u8; TE_LEN];
        let te_b = [0x01u8; TE_LEN];
        let mut ha = [0u8; PK_HASH_LEN];
        let mut hb = [0u8; PK_HASH_LEN];
        pk_hash_from_te(&te_a, &mut ha);
        pk_hash_from_te(&te_b, &mut hb);
        assert_ne!(ha, hb);
    }

    #[test]
    fn mu_deterministic() {
        let mu_pre = [0x33u8; MU_PRE_LEN];
        let mut m1 = [0u8; MU_LEN];
        let mut m2 = [0u8; MU_LEN];
        mu_from_mu_pre(&mu_pre, &mut m1);
        mu_from_mu_pre(&mu_pre, &mut m2);
        assert_eq!(m1, m2);
    }

    // ====================================================================
    // Directive B: Epoch correlation tests
    // ====================================================================

    #[test]
    fn epoch_correlation_pass_when_equal() {
        let te = build_kat_t1_te();
        // te already has epoch = 5
        let mut pk_hash = [0u8; PK_HASH_LEN];
        pk_hash_from_te(&te, &mut pk_hash);
        let mu_pre = build_kat_t2_mu_pre(&pk_hash);
        // mu_pre also has epoch = 5
        assert!(check_epoch_correlation(&mu_pre, &te).is_ok());
    }

    #[test]
    fn epoch_correlation_fails_when_mismatched() {
        let te = build_kat_t1_te();
        // te has epoch = 5
        let mut pk_hash = [0u8; PK_HASH_LEN];
        pk_hash_from_te(&te, &mut pk_hash);
        let mut mu_pre = build_kat_t2_mu_pre(&pk_hash);
        // Tamper mu_pre epoch to 99
        mu_pre[MU_PRE_EPOCH_OFF..MU_PRE_EPOCH_OFF + 8].copy_from_slice(&99u64.to_le_bytes());
        assert_eq!(
            check_epoch_correlation(&mu_pre, &te),
            Err(TranscriptError::EpochMismatch),
            "Mismatched epochs must be rejected"
        );
    }

    // ====================================================================
    // Directive E: Device ID duality tests
    // ====================================================================

    #[test]
    fn device_id32_derivation_deterministic() {
        let id16 = [0xBBu8; TE_DEVICE_ID16_LEN];
        let d1 = device_id32_from_id16(&id16);
        let d2 = device_id32_from_id16(&id16);
        assert_eq!(d1, d2);
    }

    #[test]
    fn device_id32_derivation_differs_on_different_input() {
        let id_a = [0x00u8; TE_DEVICE_ID16_LEN];
        let id_b = [0x01u8; TE_DEVICE_ID16_LEN];
        assert_ne!(device_id32_from_id16(&id_a), device_id32_from_id16(&id_b));
    }

    #[test]
    fn device_id_duality_pass_when_derived() {
        let id16 = [0xBBu8; TE_DEVICE_ID16_LEN];
        let id32 = device_id32_from_id16(&id16);

        // Build T_E with this device_id16
        let mut te = [0u8; TE_LEN];
        te[TE_DEVICE_ID16_OFF..TE_DEVICE_ID16_OFF + TE_DEVICE_ID16_LEN].copy_from_slice(&id16);

        // Build mu_pre with the correctly derived device_id32
        let mut pk_hash = [0u8; PK_HASH_LEN];
        pk_hash_from_te(&te, &mut pk_hash);
        let mut mu_pre = [0u8; MU_PRE_LEN];
        mu_pre[0..PK_HASH_LEN].copy_from_slice(&pk_hash);
        mu_pre[MU_PRE_DOMAIN_SEP_OFF..MU_PRE_DOMAIN_SEP_OFF + DOMAIN_SEP_LEN]
            .copy_from_slice(&DOMAIN_SEP);
        mu_pre[MU_PRE_VERSION_OFF] = MU_PRE_VERSION_VAL;
        mu_pre[MU_PRE_DEVICE_ID32_OFF..MU_PRE_DEVICE_ID32_OFF + MU_PRE_DEVICE_ID32_LEN]
            .copy_from_slice(&id32);

        assert!(check_device_id_duality(&mu_pre, &te).is_ok());
    }

    #[test]
    fn device_id_duality_fails_when_not_derived() {
        let id16 = [0xBBu8; TE_DEVICE_ID16_LEN];

        let mut te = [0u8; TE_LEN];
        te[TE_DEVICE_ID16_OFF..TE_DEVICE_ID16_OFF + TE_DEVICE_ID16_LEN].copy_from_slice(&id16);

        // Build mu_pre with WRONG device_id32 (raw 0xCC instead of SHAKE256)
        let mut pk_hash = [0u8; PK_HASH_LEN];
        pk_hash_from_te(&te, &mut pk_hash);
        let mut mu_pre = [0u8; MU_PRE_LEN];
        mu_pre[0..PK_HASH_LEN].copy_from_slice(&pk_hash);
        mu_pre[MU_PRE_DOMAIN_SEP_OFF..MU_PRE_DOMAIN_SEP_OFF + DOMAIN_SEP_LEN]
            .copy_from_slice(&DOMAIN_SEP);
        mu_pre[MU_PRE_VERSION_OFF] = MU_PRE_VERSION_VAL;
        mu_pre[MU_PRE_DEVICE_ID32_OFF..MU_PRE_DEVICE_ID32_OFF + MU_PRE_DEVICE_ID32_LEN].fill(0xCC); // raw bytes, NOT SHAKE256(id16)

        assert_eq!(
            check_device_id_duality(&mu_pre, &te),
            Err(TranscriptError::DeviceIdMismatch),
            "device_id32 that is NOT SHAKE256(device_id16) must be rejected"
        );
    }
}
