/* ================================================================
 * andna_core.h — AUTO-GENERATED by cbindgen, DO NOT HAND EDIT
 *
 * Regenerate: cargo run -p xtask -- gen-headers
 * Source: crates/ffi/src/lib.rs
 * ================================================================ */

#ifndef ANDNA_CORE_H
#define ANDNA_CORE_H

#include <stdint.h>
#include <stddef.h>
#include "andna_vnext_contracts.h"

/**
 * C-compatible error codes.
 *
 * cbindgen generates: ANDNA_ERR_OK, ANDNA_ERR_LENGTH, etc.
 * Integer values are ABI-stable and MUST NOT change.
 */
typedef enum AndnaErr {
  ANDNA_ERR_OK = 0,
  ANDNA_ERR_LENGTH = 1,
  ANDNA_ERR_MU_PRE = 2,
  ANDNA_ERR_TE = 3,
  ANDNA_ERR_SIG = 4,
  ANDNA_ERR_PK_HASH_MISMATCH = 5,
  ANDNA_ERR_SIG_INVALID = 6,
  /**
   * Directive B: mu_pre.epoch != T_E.epoch
   */
  ANDNA_ERR_EPOCH_MISMATCH = 7,
  /**
   * Directive E: device_id32 != SHAKE256(device_id16, 32)
   */
  ANDNA_ERR_DEVICE_ID_MISMATCH = 8,
  /**
   * Catch-all for panics caught at the FFI boundary (Directive C)
   */
  ANDNA_ERR_INTERNAL = 100,
} AndnaErr;

/**
 * Parse hot-path fields from mu_pre for pre-crypto gating.
 *
 * # Safety
 * - `mu_pre` must point to at least `mu_pre_len` readable bytes
 * - `out_device_id32` must point to 32 writable bytes
 * - `out_epoch` must point to a valid u64
 * - `out_sid` must point to 32 writable bytes
 */
AndnaErr andna_parse_mu_pre_header(const uint8_t *mu_pre,
                                   size_t mu_pre_len,
                                   uint8_t *out_device_id32,
                                   uint64_t *out_epoch,
                                   uint8_t *out_sid);

/**
 * Return a human-readable error string for the given error code.
 *
 * The returned pointer is a static string — valid for the lifetime of the process.
 * Caller MUST NOT free it. This function cannot panic.
 */
const char *andna_strerror(AndnaErr err);

/**
 * Verify a packed v2 frame (4030 bytes).
 *
 * # Safety
 * - `frame` must point to at least `frame_len` readable bytes
 */
AndnaErr andna_verify_frame_v2(const uint8_t *frame,
                               size_t frame_len);

/**
 * Verify mu_pre + T_E + signature.
 *
 * # Safety
 * - `mu_pre` must point to at least `mu_pre_len` readable bytes
 * - `te` must point to at least `te_len` readable bytes
 * - `sig` must point to at least `sig_len` readable bytes
 * - All pointers must be valid for the duration of the call
 */
AndnaErr andna_verify_vnext(const uint8_t *mu_pre,
                            size_t mu_pre_len,
                            const uint8_t *te,
                            size_t te_len,
                            const uint8_t *sig,
                            size_t sig_len);

/**
 * Return the library version string (NUL-terminated).
 *
 * The returned pointer is a static string — valid for the lifetime of the process.
 */
const char *andna_version(void);

#endif /* ANDNA_CORE_H */
