/* ================================================================
 * andna_core.h — AUTO-GENERATED by cbindgen, DO NOT HAND EDIT
 *
 * Regenerate: cargo run -p xtask -- gen-headers
 * Source: crates/ffi/src/lib.rs
 *
 * NOTE:
 * This local copy was manually patched to expose andna_init() because
 * local header generation was blocked by Windows Application Control
 * / missing cbindgen in the temporary Docker header-generation path.
 * Re-run xtask/cbindgen in CI or an approved build lane when available.
 * ================================================================ */

#ifndef ANDNA_CORE_H
#define ANDNA_CORE_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stddef.h>
#include "andna_vnext_contracts.h"


/**
 * C-compatible error codes.
 *
 * cbindgen generates: ANDNA_ERR_OK, ANDNA_ERR_LENGTH, etc.
 * Integer values are ABI-stable and MUST NOT change.
 */
typedef enum AndnaErr {
  ANDNA_ERR_OK = 0,
  ANDNA_ERR_LENGTH = 1,
  ANDNA_ERR_MU_PRE = 2,
  ANDNA_ERR_TE = 3,
  ANDNA_ERR_SIG = 4,
  ANDNA_ERR_PK_HASH_MISMATCH = 5,
  ANDNA_ERR_SIG_INVALID = 6,
  /**
   * Directive B: mu_pre.epoch != T_E.epoch
   */
  ANDNA_ERR_EPOCH_MISMATCH = 7,
  /**
   * Directive E: device_id32 != SHAKE256(device_id16, 32)
   */
  ANDNA_ERR_DEVICE_ID_MISMATCH = 8,
  /**
   * Catch-all for panics caught at the FFI boundary (Directive C)
   */
  ANDNA_ERR_INTERNAL = 100,
} AndnaErr;

/**
 * Initialize the AN-DNA FIPS module.
 *
 * Must be called before any cryptographic service.
 * Runs power-up self-tests and transitions the module to Approved Mode.
 *
 * Returns ANDNA_ERR_OK on success, ANDNA_ERR_INTERNAL on failure.
 */
enum AndnaErr andna_init(void);

/**
 * Verify mu_pre + T_E + signature.
 *
 * # Safety
 * - `mu_pre` must point to at least `mu_pre_len` readable bytes
 * - `te` must point to at least `te_len` readable bytes
 * - `sig` must point to at least `sig_len` readable bytes
 * - All pointers must be valid for the duration of the call
 */
enum AndnaErr andna_verify_vnext(const uint8_t *mu_pre,
                                 uintptr_t mu_pre_len,
                                 const uint8_t *te,
                                 uintptr_t te_len,
                                 const uint8_t *sig,
                                 uintptr_t sig_len);

/**
 * Verify a packed v2 frame (4030 bytes).
 *
 * Gate 2 v1: Rust-owned audit sink appends one record per call.
 *
 * # Safety
 * - `frame` must point to at least `frame_len` readable bytes
 */
enum AndnaErr andna_verify_frame_v2(const uint8_t *frame, uintptr_t frame_len);

/**
 * Parse hot-path fields from mu_pre for pre-crypto gating.
 *
 * # Safety
 * - `mu_pre` must point to at least `mu_pre_len` readable bytes
 * - `out_device_id32` must point to 32 writable bytes
 * - `out_epoch` must point to a valid u64
 * - `out_sid` must point to 32 writable bytes
 */
enum AndnaErr andna_parse_mu_pre_header(const uint8_t *mu_pre,
                                        uintptr_t mu_pre_len,
                                        uint8_t *out_device_id32,
                                        uint64_t *out_epoch,
                                        uint8_t *out_sid);

/**
 * Generate a complete, validly-signed 4030-byte test frame (Frame v2).
 *
 * Purpose: provide a real-signed frame so Python+Rust engines can agree on ACCEPT.
 * This is only meaningful when the real signature backend is enabled.
 *
 * Keygen → build T_E → build mu_pre → sign μ → pack frame.
 *
 * # Safety
 * - `out_ptr` must point to at least `out_len` writable bytes.
 * - `out_len` MUST equal FRAME_V2_LEN.
 */
enum AndnaErr andna_gen_test_frame(uint8_t *out_ptr, uintptr_t out_len);

/**
 * Export the current Rust-owned audit log as deterministic JSONL.
 *
 * # Safety
 * - `path` must be a valid NUL-terminated UTF-8 string pointer.
 * - The file will be overwritten.
 */
enum AndnaErr andna_audit_export_jsonl(const char *path);

/**
 * Return a human-readable error string for the given error code.
 *
 * The returned pointer is a static `&str` — valid for the lifetime of the process.
 * Caller MUST NOT free it. This function cannot panic.
 */
const char *andna_strerror(enum AndnaErr err);

/**
 * Return the library version string (NUL-terminated).
 *
 * The returned pointer is a static string — valid for the lifetime of the process.
 * This function cannot panic.
 */
const char *andna_version(void);

#endif /* ANDNA_CORE_H */
