/* ================================================================
 * andna_vnext_contracts.h — AUTO-GENERATED, DO NOT HAND EDIT
 *
 * Generated by: cargo run -p contracts_codegen -- generate
 * Source of truth: crates/contracts/src/lib.rs
 * ================================================================ */

#ifndef ANDNA_VNEXT_CONTRACTS_H
#define ANDNA_VNEXT_CONTRACTS_H

#include <stdint.h>
#include <stddef.h>

/* ── ML-DSA-44 Ring Constants (FIPS 204, Category 2) ── */
#define ANDNA_MLDSA44_Q 8380417u
#define ANDNA_MLDSA44_N 256u
#define ANDNA_MLDSA44_K 4u
#define ANDNA_MLDSA44_ELL 4u
#define ANDNA_MLDSA44_D 13u
#define ANDNA_MLDSA44_ETA 2u
#define ANDNA_MLDSA44_TAU 39u
#define ANDNA_MLDSA44_OMEGA 80u
#define ANDNA_MLDSA44_GAMMA1 131072u
#define ANDNA_MLDSA44_GAMMA2 95232u
#define ANDNA_MLDSA44_ALPHA 190464u
#define ANDNA_MLDSA44_BETA 78u

/* ── Domain Separation ── */
#define ANDNA_DOMAIN_SEP_LEN 9u
/* Phase-1 canonical: "ANDNAAUTH" (no hyphen, no NUL) */
/* Hex: 41 4E 44 4E 41 41 55 54 48 */
static const uint8_t ANDNA_DOMAIN_SEP[9] = {
    0x41, 0x4E, 0x44, 0x4E, 0x41, 0x41, 0x55, 0x54, 0x48
}; /* A N D N A A U T H */
/* V2 (future): "ANDNA-AUTH" = 10 bytes, under MU_PRE_VERSION 0x02 */
#define ANDNA_DOMAIN_SEP_V2_LEN 10u

/* ── mu_pre Layout (274 bytes) ── */
#define ANDNA_MU_PRE_LEN 274u
#define ANDNA_MU_PRE_PK_HASH_OFF 0u
#define ANDNA_MU_PRE_PK_HASH_LEN 64u
#define ANDNA_MU_PRE_DOMAIN_SEP_OFF 64u
#define ANDNA_MU_PRE_DOMAIN_SEP_LEN 9u
#define ANDNA_MU_PRE_VERSION_OFF 73u
#define ANDNA_MU_PRE_VERSION_LEN 1u
#define ANDNA_MU_PRE_VERSION_VAL 0x01u
#define ANDNA_MU_PRE_DEVICE_ID32_OFF 74u
#define ANDNA_MU_PRE_DEVICE_ID32_LEN 32u
#define ANDNA_MU_PRE_EPOCH_OFF 106u
#define ANDNA_MU_PRE_EPOCH_LEN 8u
#define ANDNA_MU_PRE_SID_OFF 114u
#define ANDNA_MU_PRE_SID_LEN 32u
#define ANDNA_MU_PRE_ND_OFF 146u
#define ANDNA_MU_PRE_ND_LEN 32u
#define ANDNA_MU_PRE_NS_OFF 178u
#define ANDNA_MU_PRE_NS_LEN 32u
#define ANDNA_MU_PRE_CTX_HASH_OFF 210u
#define ANDNA_MU_PRE_CTX_HASH_LEN 32u
#define ANDNA_MU_PRE_POLICY_HASH_OFF 242u
#define ANDNA_MU_PRE_POLICY_HASH_LEN 32u

/* ── T_E Layout ── */
#define ANDNA_TE_RHO_OFF 0u
#define ANDNA_TE_RHO_LEN 32u
#define ANDNA_TE_T1_OFF 32u
#define ANDNA_TE_T1_LEN 1280u
#define ANDNA_TE_EPOCH_OFF 1312u
#define ANDNA_TE_EPOCH_LEN 8u
#define ANDNA_TE_DEVICE_ID16_OFF 1320u
#define ANDNA_TE_DEVICE_ID16_LEN 16u
#define ANDNA_TE_V1_LEN 1336u
#define ANDNA_TE_V2_LEN 1352u
#define ANDNA_TE_LEN 1336u

/* ── ML-DSA-44 Signature (2420 bytes) ── */
#define ANDNA_SIG_Z_OFF 0u
#define ANDNA_SIG_Z_LEN 2304u
#define ANDNA_SIG_H_OFF 2304u
#define ANDNA_SIG_H_LEN 84u
#define ANDNA_SIG_C_TILDE_OFF 2388u
#define ANDNA_SIG_C_TILDE_LEN 32u
#define ANDNA_SIG_LEN 2420u

/* ── Frame v2 (fixed 4030 bytes) ── */
#define ANDNA_FRAME_V2_MU_PRE_OFF 0u
#define ANDNA_FRAME_V2_TE_OFF 274u
#define ANDNA_FRAME_V2_SIG_OFF 1610u
#define ANDNA_FRAME_V2_LEN 4030u

/* ── Anti-Drift Guards ── */
_Static_assert(ANDNA_MU_PRE_LEN == 274u, "ANDNA_MU_PRE_LEN drift detected");
_Static_assert(ANDNA_TE_V1_LEN == 1336u, "ANDNA_TE_V1_LEN drift detected");
_Static_assert(ANDNA_TE_V2_LEN == 1352u, "ANDNA_TE_V2_LEN drift detected");
_Static_assert(ANDNA_TE_LEN == 1336u, "ANDNA_TE_LEN drift detected");
_Static_assert(ANDNA_SIG_LEN == 2420u, "ANDNA_SIG_LEN drift detected");
_Static_assert(ANDNA_FRAME_V2_LEN == 4030u, "ANDNA_FRAME_V2_LEN drift detected");
_Static_assert(ANDNA_MLDSA44_BETA == 78u, "ANDNA_MLDSA44_BETA drift detected");
_Static_assert(ANDNA_MLDSA44_GAMMA1 == 131072u, "ANDNA_MLDSA44_GAMMA1 drift detected");
_Static_assert(ANDNA_MLDSA44_GAMMA2 == 95232u, "ANDNA_MLDSA44_GAMMA2 drift detected");

/* ── Field-Sum Guards ── */
_Static_assert(
    ANDNA_MU_PRE_PK_HASH_LEN + ANDNA_MU_PRE_DOMAIN_SEP_LEN +
    ANDNA_MU_PRE_VERSION_LEN + ANDNA_MU_PRE_DEVICE_ID32_LEN +
    ANDNA_MU_PRE_EPOCH_LEN + ANDNA_MU_PRE_SID_LEN +
    ANDNA_MU_PRE_ND_LEN + ANDNA_MU_PRE_NS_LEN +
    ANDNA_MU_PRE_CTX_HASH_LEN + ANDNA_MU_PRE_POLICY_HASH_LEN
    == ANDNA_MU_PRE_LEN,
    "mu_pre field sum != MU_PRE_LEN");
_Static_assert(
    ANDNA_TE_RHO_LEN + ANDNA_TE_T1_LEN +
    ANDNA_TE_EPOCH_LEN + ANDNA_TE_DEVICE_ID16_LEN
    == ANDNA_TE_V1_LEN,
    "TE field sum != TE_V1_LEN");
_Static_assert(
    ANDNA_SIG_Z_LEN + ANDNA_SIG_H_LEN + ANDNA_SIG_C_TILDE_LEN
    == ANDNA_SIG_LEN,
    "sig field sum != SIG_LEN");
_Static_assert(
    ANDNA_MU_PRE_LEN + ANDNA_TE_LEN + ANDNA_SIG_LEN
    == ANDNA_FRAME_V2_LEN,
    "frame field sum != FRAME_V2_LEN");

/* ── mu_pre Offset-Chain Contiguity Guards ── */
_Static_assert(ANDNA_MU_PRE_PK_HASH_OFF == 0u,
    "mu_pre pk_hash must start at 0");
_Static_assert(ANDNA_MU_PRE_DOMAIN_SEP_OFF ==
    ANDNA_MU_PRE_PK_HASH_OFF + ANDNA_MU_PRE_PK_HASH_LEN,
    "mu_pre domain_sep offset non-contiguous");
_Static_assert(ANDNA_MU_PRE_VERSION_OFF ==
    ANDNA_MU_PRE_DOMAIN_SEP_OFF + ANDNA_MU_PRE_DOMAIN_SEP_LEN,
    "mu_pre version offset non-contiguous");
_Static_assert(ANDNA_MU_PRE_DEVICE_ID32_OFF ==
    ANDNA_MU_PRE_VERSION_OFF + ANDNA_MU_PRE_VERSION_LEN,
    "mu_pre device_id32 offset non-contiguous");
_Static_assert(ANDNA_MU_PRE_EPOCH_OFF ==
    ANDNA_MU_PRE_DEVICE_ID32_OFF + ANDNA_MU_PRE_DEVICE_ID32_LEN,
    "mu_pre epoch offset non-contiguous");
_Static_assert(ANDNA_MU_PRE_SID_OFF ==
    ANDNA_MU_PRE_EPOCH_OFF + ANDNA_MU_PRE_EPOCH_LEN,
    "mu_pre sid offset non-contiguous");
_Static_assert(ANDNA_MU_PRE_ND_OFF ==
    ANDNA_MU_PRE_SID_OFF + ANDNA_MU_PRE_SID_LEN,
    "mu_pre N_d offset non-contiguous");
_Static_assert(ANDNA_MU_PRE_NS_OFF ==
    ANDNA_MU_PRE_ND_OFF + ANDNA_MU_PRE_ND_LEN,
    "mu_pre N_s offset non-contiguous");
_Static_assert(ANDNA_MU_PRE_CTX_HASH_OFF ==
    ANDNA_MU_PRE_NS_OFF + ANDNA_MU_PRE_NS_LEN,
    "mu_pre ctx_hash offset non-contiguous");
_Static_assert(ANDNA_MU_PRE_POLICY_HASH_OFF ==
    ANDNA_MU_PRE_CTX_HASH_OFF + ANDNA_MU_PRE_CTX_HASH_LEN,
    "mu_pre policy_hash offset non-contiguous");
_Static_assert(ANDNA_MU_PRE_POLICY_HASH_OFF + ANDNA_MU_PRE_POLICY_HASH_LEN
    == ANDNA_MU_PRE_LEN,
    "mu_pre tail does not reach MU_PRE_LEN");

/* ── T_E Offset-Chain Contiguity Guards ── */
_Static_assert(ANDNA_TE_RHO_OFF == 0u,
    "TE rho must start at 0");
_Static_assert(ANDNA_TE_T1_OFF ==
    ANDNA_TE_RHO_OFF + ANDNA_TE_RHO_LEN,
    "TE t1 offset non-contiguous");
_Static_assert(ANDNA_TE_EPOCH_OFF ==
    ANDNA_TE_T1_OFF + ANDNA_TE_T1_LEN,
    "TE epoch offset non-contiguous");
_Static_assert(ANDNA_TE_DEVICE_ID16_OFF ==
    ANDNA_TE_EPOCH_OFF + ANDNA_TE_EPOCH_LEN,
    "TE device_id16 offset non-contiguous");
_Static_assert(ANDNA_TE_DEVICE_ID16_OFF + ANDNA_TE_DEVICE_ID16_LEN
    == ANDNA_TE_V1_LEN,
    "TE tail does not reach TE_V1_LEN");

/* ── Signature Offset-Chain Contiguity Guards ── */
_Static_assert(ANDNA_SIG_Z_OFF == 0u,
    "sig z must start at 0");
_Static_assert(ANDNA_SIG_H_OFF ==
    ANDNA_SIG_Z_OFF + ANDNA_SIG_Z_LEN,
    "sig h offset non-contiguous");
_Static_assert(ANDNA_SIG_C_TILDE_OFF ==
    ANDNA_SIG_H_OFF + ANDNA_SIG_H_LEN,
    "sig c_tilde offset non-contiguous");
_Static_assert(ANDNA_SIG_C_TILDE_OFF + ANDNA_SIG_C_TILDE_LEN
    == ANDNA_SIG_LEN,
    "sig tail does not reach SIG_LEN");

#endif /* ANDNA_VNEXT_CONTRACTS_H */
